--DB: ammdb; user: nerd; pass: nerd:

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Davide
 * Created: May 18, 2017
 */

CREATE TABLE utenti(
utente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(256),
cognome VARCHAR(256),
imgProfilo VARCHAR(256),
motto VARCHAR(256),
dob VARCHAR(10),
username VARCHAR(256),
password VARCHAR(256) NOT NULL
);

CREATE TABLE gruppi(
gruppo_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
admin integer,
FOREIGN KEY (admin) REFERENCES utenti(utente_id),
title VARCHAR(32),
descrizione VARCHAR(200)
);

CREATE TABLE subs(
subscriber INTEGER,
FOREIGN KEY(subscriber) REFERENCES utenti(utente_id),
buddie INTEGER,
FOREIGN KEY(buddie) REFERENCES gruppi(gruppo_id)
);

CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);

CREATE TABLE posts(
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status  VARCHAR(1024),
    content VARCHAR(512),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(postType_id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(utente_id),
    gruppo INTEGER,
    FOREIGN KEY (gruppo) REFERENCES gruppi(gruppo_id)
);
--Popolamento della tabella utenti

INSERT INTO utenti(utente_id,nome,cognome,imgProfilo,motto,dob,username,password)
VALUES (default,
        'Marco',
        'Fenice',
        'img/MarcoFenice.jpg',
        'Odio zanzare, mosche e pulci!',
        '18/02/2016',
        'marcus1',
        '1'
);

INSERT INTO utenti(utente_id,nome,cognome,imgProfilo,motto,dob,username,password)
VALUES (default,
        'Massimo',
        'Dolore',
        'img/MassimoDolore.jpg',
        'Lo slow motion è uno stile di vita',
        '09/02/1994',
        'max1',
        '1'
);

INSERT INTO utenti(utente_id,nome,cognome,imgProfilo,motto,dob,username,password)
VALUES (default,
        'Nathan',
        'Drago',
        'img/NathanDrago.jpg',
        'Sono follemente innamorato di Lara Croft',
        '14/05/2000',
        'nathan1',
        '1'
);

--Popolamento tabella Gruppi
INSERT INTO gruppi(gruppo_id,admin,title, descrizione)
VALUES(default,
        1,
        'Xboxari',
        'Il primo gruppo per i fan di casa Microsoft!'
);

--Popolamento tabella PostType
INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'TEXT');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'IMAGE');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'URL');

--Popolamento tabella Post

INSERT INTO posts (post_id, status, type, author, gruppo)
VALUES (default,
        'Odio gli insetti! Mi fanno proprio schifo!',
        1,
        1,
        1
        );

INSERT INTO posts (post_id, status, content, type, author)
VALUES (default,
        'Amo questo film e lo slow motion!',
        'img/Neo.jpg',
        2,
        2
        );

INSERT INTO posts (post_id, status, content, type, author)
VALUES (default,
        'Consiglio a tutti di leggere questo articolo! Che storia incredibile!"',
        'http://www.lercio.it/terrapiattista-precipita-dal-bordo-del-pianeta-ma-si-salva-afferrando-una-scia-chimica/',
        3,
        3
        );